In [1]:
import pandas
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier

In [2]:
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'class']
dataset = pandas.read_csv("iris.csv", names=names)

In [3]:
 
print(dataset.shape)

(151, 5)


In [4]:

print(dataset.groupby('class').size())

class
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Species             1
dtype: int64


In [5]:
dataset.drop([0],axis=0,inplace=True)

In [6]:

array = dataset.values
X = array[:,0:4]
Y = array[:,4]
t_size = 0.20
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size,
random_state=seed)

In [7]:
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train)
predictions = knn.predict(X_test)
print(accuracy_score(Y_test, predictions))
print(confusion_matrix(Y_test, predictions))
print(classification_report(Y_test, predictions))

0.9
[[ 7  0  0]
 [ 0 11  1]
 [ 0  2  9]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         7
Iris-versicolor       0.85      0.92      0.88        12
 Iris-virginica       0.90      0.82      0.86        11

       accuracy                           0.90        30
      macro avg       0.92      0.91      0.91        30
   weighted avg       0.90      0.90      0.90        30



In [8]:
seed = 7
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size,
random_state=seed)
for i in range(1,10):
  knn = KNeighborsClassifier(i)
  knn.fit(X_train, Y_train)
  predictions = knn.predict(X_test)
  print(f'k = {i}, Accuracy= ', end='')
  print(accuracy_score(Y_test, predictions))

k = 1, Accuracy= 0.9
k = 2, Accuracy= 0.9333333333333333
k = 3, Accuracy= 0.9
k = 4, Accuracy= 0.9333333333333333
k = 5, Accuracy= 0.9
k = 6, Accuracy= 0.8666666666666667
k = 7, Accuracy= 0.8666666666666667
k = 8, Accuracy= 0.9
k = 9, Accuracy= 0.9


In [9]:
for i in range(1,11):
  X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=t_size,
  random_state=i)
  knn = KNeighborsClassifier()
  knn.fit(X_train, Y_train)
  predictions = knn.predict(X_test)
  print(f'seed = {i}, Accuracy= ', end='')
  print(accuracy_score(Y_test, predictions))

seed = 1, Accuracy= 1.0
seed = 2, Accuracy= 1.0
seed = 3, Accuracy= 0.9666666666666667
seed = 4, Accuracy= 0.9666666666666667
seed = 5, Accuracy= 0.9333333333333333
seed = 6, Accuracy= 0.9666666666666667
seed = 7, Accuracy= 0.9
seed = 8, Accuracy= 0.9
seed = 9, Accuracy= 1.0
seed = 10, Accuracy= 0.9666666666666667


In [10]:
test1 = pandas.read_csv("datatraining.txt")
test2 = pandas.read_csv("datatest2.txt")
test3 = pandas.read_csv("datatraining.txt")
print(test1.head())
print(test2.head())
print(test3.head())

                  date  Temperature  Humidity  Light     CO2  HumidityRatio  \
1  2015-02-04 17:51:00        23.18   27.2720  426.0  721.25       0.004793   
2  2015-02-04 17:51:59        23.15   27.2675  429.5  714.00       0.004783   
3  2015-02-04 17:53:00        23.15   27.2450  426.0  713.50       0.004779   
4  2015-02-04 17:54:00        23.15   27.2000  426.0  708.25       0.004772   
5  2015-02-04 17:55:00        23.10   27.2000  426.0  704.50       0.004757   

   Occupancy  
1          1  
2          1  
3          1  
4          1  
5          1  
                  date  Temperature   Humidity       Light          CO2  \
1  2015-02-11 14:48:00      21.7600  31.133333  437.333333  1029.666667   
2  2015-02-11 14:49:00      21.7900  31.000000  437.333333  1000.000000   
3  2015-02-11 14:50:00      21.7675  31.122500  434.000000  1003.750000   
4  2015-02-11 14:51:00      21.7675  31.122500  439.000000  1009.500000   
5  2015-02-11 14:51:59      21.7900  31.133333  437.333333  

In [11]:
print(test1.shape)
print(test2.shape)
print(test3.shape)

(8143, 7)
(9752, 7)
(8143, 7)


In [12]:
test3=test3.drop(["date"],axis=1)
test1=test1.drop(["date"],axis=1)


In [13]:
from datetime import datetime;
array = test3.values
X_test3 = array[:,0:5]
Y_test3 = array[:,5]
array = test1.values
X_test1 = array[:,0:5]
Y_test1 = array[:,5]

In [14]:
knn = KNeighborsClassifier()
knn.fit(X_test3,Y_test3)
predictions = knn.predict(X_test1)
print(accuracy_score(Y_test1, predictions))
print(confusion_matrix(Y_test1, predictions))
print(classification_report(Y_test1, predictions))

0.992140488763355
[[6361   53]
 [  11 1718]]
              precision    recall  f1-score   support

         0.0       1.00      0.99      0.99      6414
         1.0       0.97      0.99      0.98      1729

    accuracy                           0.99      8143
   macro avg       0.98      0.99      0.99      8143
weighted avg       0.99      0.99      0.99      8143



In [15]:
for i in range (1,11) :
    knn = KNeighborsClassifier(n_neighbors = i)
    knn.fit(X_test3, Y_test3)
    predictions = knn.predict(X_test1)
    print("k = ",i,", ","Accuracy = ",accuracy_score(Y_test1, predictions))

k =  1 ,  Accuracy =  1.0
k =  2 ,  Accuracy =  0.9952106103401694
k =  3 ,  Accuracy =  0.9948421957509518
k =  4 ,  Accuracy =  0.993614147120226
k =  5 ,  Accuracy =  0.992140488763355
k =  6 ,  Accuracy =  0.992140488763355
k =  7 ,  Accuracy =  0.9906668304064841
k =  8 ,  Accuracy =  0.9902984158172664
k =  9 ,  Accuracy =  0.9896843915019035
k =  10 ,  Accuracy =  0.9899300012280486


In [16]:
import numpy as np
A = dataset["class"]
B = dataset.drop(["class"],axis=1);
B = B[1:len(dataset)];
A = A[1:len(dataset)]

In [17]:
class KNN:
  def __init__(self , k=5):
    self.k = k
    pass;
  def DistCal(self,x ,y):
    sum = 0.0;
    for i in range(0,len(x)):
      try:
        sum += (pow((x[i] - y[i]),2)) / (x[i] + y[i]) 
      except ZeroDivisionError:
        sum += 0;
    return sum;
  def get_adjacent(self,B,point):
    dist = [];
    indexes = [];
    for i in range(0,len(B)):
      sl , sw , pl , pw = B.iloc[i,:]
      result = self.DistCal(  point,[float(sl),float(sw),float(pl),float(pw)]  );
      indexes.append(i);
      
      dist.append(result);
                  
    return sorted(zip( dist,indexes))[:self.k]
  def find_hi(self,mapping):
    max , max_index = -999 , -1;
    for k in mapping.keys():
      if(mapping[k] > max):
        max = mapping[k];
        max_index =  k;
    return max_index;
  def predict(self,adjacent , y):
    results = [];
    dict1 = {};
    for score , index in adjacent:
      results.append(y.iloc[index]);
      try:

        dict1[y.iloc[index] ] +=1;
      except:
        dict1[y.iloc[index]] = 1;
    if(len(np.unique(adjacent)) != len(adjacent)):
      
      hi = self.find_hi(dict1);
      return hi;

    return y.iloc[adjacent[0][1]];

In [18]:
def acc_score(actual , pred):
  correct = 0;
  for i in range(0 , len(pred)):
    if(actual[i] == pred[i]):
      correct +=1;
  return correct/len(actual);
knn = KNN();
outputs = [];
for i in range(1,len(B)):
  sl , sw , pl ,pw = B.iloc[i , :];
  prediction = knn.get_adjacent(B , [float(sl) ,float(sw) , float(pl) ,float(pw)]);
  x =knn.predict(prediction , A);
  outputs.append(x);
print(acc_score(A.to_list() , outputs))

0.9463087248322147
